In [52]:
import numpy as np
import gym # pip intall gym
import random

In [53]:
env = gym.make('FrozenLake-v1', is_slippery = False) # Instantiating gym object

In [54]:
action_space_size = env.action_space.n # Number of possible actions in each of these states in the frozen lake game.
state_space_size = env.observation_space.n # Number of states for the frozen lake game

qtable = np.zeros((state_space_size, action_space_size)) # Creating q tabel from state spaces and action space states.
print("Q Table\n",qtable) 

Q Table
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
total_episodes = 10000 # Number of times we want our agent to play the game to fill the q-table.
learning_rate = 0.2 # Learning Rate 
max_steps = 100
gamma = 0.99

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [56]:
rewards = []

for episode in range(total_episodes):
    state, info = env.reset()
    step = 0
    done = False
    total_rewards = 0
    for step in range(max_steps):
        
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) # Exploit
        else:
            action = env.action_space.sample() # Explore

        new_state, reward, done, truncated, info = env.step(action)
        
        max_new_state = np.max(qtable[new_state,:])
        
        qtable[state,action] = qtable[state, action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        total_rewards += reward
        
        state = new_state
        if done:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) # Decreasing the probability of exploring as episodes increase.
    rewards.append(total_rewards) 
    
print("Score:", str(sum(rewards)/total_episodes*100) + "%")
print(qtable)

Score: 87.92%
[[0.94148015 0.95099005 0.93206535 0.94148015]
 [0.94148015 0.         0.92190736 0.93201897]
 [0.93197552 0.29134814 0.6311653  0.8573256 ]
 [0.79744731 0.         0.04112673 0.34098788]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.97102458 0.         0.44659748]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.96960674 0.99       0.         0.92813135]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [57]:
env.reset()

for episode in range(1):
    state, info = env.reset()
    step = 0
    done = False
    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()

Episode: 1
Number of Steps: 5


# SARSA

In [58]:
rewards = []

for episode in range(total_episodes):
    state, info = env.reset()
    step = 0
    done = False
    total_rewards = 0
    for step in range(max_steps):
        
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state,:]) # Exploit
        else:
            action = env.action_space.sample() # Explore

        new_state, reward, done, truncated, info = env.step(action)

        if random.uniform(0,1) > epsilon:
            new_action = np.argmax(qtable[new_state,:]) # Exploit
        else:
            new_action = env.action_space.sample() # Explore
        
        sarsa_new_state = np.max(qtable[new_state, new_action])
        
        qtable[state,action] = qtable[state, action] + learning_rate*(reward+gamma*sarsa_new_state-qtable[state,action])
        total_rewards += reward
        
        state = new_state
        if done:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) # Decreasing the probability of exploring as episodes increase.
    rewards.append(total_rewards) 
    
print("Score:", str(sum(rewards)/total_episodes*100) + "%")
print(qtable)

Score: 86.41%
[[0.74125994 0.95087443 0.65490817 0.71128461]
 [0.71311856 0.         0.53595437 0.5363225 ]
 [0.56712499 0.50275402 0.49343868 0.53398481]
 [0.53625641 0.         0.32055347 0.5085363 ]
 [0.78017015 0.96055084 0.         0.81089758]
 [0.         0.         0.         0.        ]
 [0.         0.94428427 0.         0.56086826]
 [0.         0.         0.         0.        ]
 [0.77116278 0.         0.9702876  0.78224882]
 [0.78449732 0.9800986  0.82328392 0.        ]
 [0.96895191 0.98999999 0.         0.84103701]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9788769  0.99       0.96015407]
 [0.97978952 0.98941709 1.         0.78401799]
 [0.         0.         0.         0.        ]]
